### ISSUE TITLE
can't filter fake ip when using 114 dns

### ISSUE THREAD

**Issue by sadoneli** [clowwindy/ChinaDNS#100]
I compliled ChinaDNS on asus Merlin firmware using merlin toolchain,
ChinaDNS works fine but with some issue of filter fake ip
My ISP is China Mobile, and I am in Wuhan

# my chinadns command (chnroute up to date;port 1054 for dnscrypt-proxy;port 1055 for ss-tunnel requset 8.8.8.8)
chinadns -p 1053 -s 114.114.114.114,127.0.0.1:1054,127.0.0.1:1055 -m -d -c /jffs/ss/redchn/chnroute.txt

# chinadns log when i dig google.com
Wed Jun 17 19:04:35 2015 request google.com
Wed Jun 17 19:04:35 2015 response google.com from 114.114.114.114:53 - 211.137.57.102, 120.202.249.230, 120.202.249.205, 211.137.57.99, 211.137.57.101, pass
Wed Jun 17 19:04:35 2015 response google.com from 114.114.114.114:53 - 120.202.249.230, 211.137.57.102, pass
Wed Jun 17 19:04:35 2015 response google.com from 114.114.114.114:53 - 211.137.57.99, 211.137.57.101, 211.137.57.102, 120.202.249.230, 120.202.249.205, pass
Wed Jun 17 19:04:35 2015 response google.com from 114.114.114.114:53 - 216.58.221.78, filter
Wed Jun 17 19:04:35 2015 response google.com from 127.0.0.1:1054 - 216.58.221.206, pass
Wed Jun 17 19:04:35 2015 response google.com from 127.0.0.1:1055 - 173.194.126.137, 173.194.126.131, 173.194.126.133, 173.194.126.132, 173.194.126.134, 173.194.126.130, 173.194.126.129, 173.194.126.136, 173.194.126.128, 173.194.126.142, 173.194.126.135, pass
 
google.com get primary ip address 211.137.57.102 from 114 dns, which was found a China IP, and it was included in the chnroute.txt, how did this ip get pass?

# my dig result
C:\Users\lixin>dig google.com

; <<>> DiG 9.9.7 <<>> google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 35958
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;google.com.                    IN      A

;; ANSWER SECTION:
google.com.             212     IN      A       211.137.57.102
google.com.             212     IN      A       120.202.249.230
google.com.             212     IN      A       120.202.249.205
google.com.             212     IN      A       211.137.57.99
google.com.             212     IN      A       211.137.57.101

;; Query time: 16 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Wed Jun 17 19:03:17 ?D1ú±ê×?ê±?? 2015
;; MSG SIZE  rcvd: 108

Wed Jun 17 19:16:14 2015 request twitter.com
Wed Jun 17 19:16:14 2015 response twitter.com from 114.114.114.114:53 - 203.98.7.65, filter
Wed Jun 17 19:16:14 2015 response twitter.com from 114.114.114.114:53 - 78.16.49.15, filter
Wed Jun 17 19:16:14 2015 response twitter.com from 114.114.114.114:53 - 78.16.49.15, filter
Wed Jun 17 19:16:14 2015 response twitter.com from 114.114.114.114:53 - 203.98.7.65, filter
Wed Jun 17 19:16:14 2015 response twitter.com from 127.0.0.1:1055 - 199.16.158.179, 199.16.158.168, pass

I don't know what is the problem, is there any chance that DNS compression pointer mutation (-m) not working?

**Comment by sadoneli** [comment]
PS:when I using ali dns:223.5.5.5, chinadns works just fine and no fake ip get pass.

**Comment by clowwindy** [comment]
Since you got multiple responses from 114, which is unexpected, I believe something is wrong. For example, your ISP may want to hijack your traffic and insert ads to your page. ShadowVPN isn't prepared for this scenario.
