### ISSUE TITLE
Move precompiled binaries off SourceForge

### ISSUE THREAD

**Issue by riobard** [clowwindy/ChinaDNS#101]
SourceForge cannot be trusted any more. Ideally we should package it as part of GitHub releases.

**Comment by clowwindy** [comment]
What happened to SourceForge?

**Comment by tony1016** [comment]
Google mark sourceforge as malware site

**Comment by riobard** [comment]
Apparently SourceForge is running out of money and without a viable business plan to sustain itself. As a result they are replacing hosted binaries with adware versions to make money. We can no longer trust such a player.

**Comment by clowwindy** [comment]
Well, we'll move to GitHub then.

**Comment by clowwindy** [comment]
Done.
https://github.com/clowwindy/ChinaDNS/releases
