### ISSUE TITLE
vpn重新连接后的异常

### ISSUE THREAD

**Issue by supertinytiger** [clowwindy/ChinaDNS#102]
用chinadns搭建dns server后，如果将此服务器连接国外的vpn断开一段时间后再将vpn恢复连接，所有对国外域名的查询都没有返回结果。从log中可以看到两个foreign dns server (google and opendns servers) 不再提供response。

环境：中国电信，raspian，dns server设置了境外ip走vpn。

以facebook查询为例，VPN正常时的log：

sudo ./chinadns -m -c chnroute.txt -s 114.114.114.11414.114.115.115,8.8.8.8,8.8.4.4,208.67.222.222:443,208.67.222.222:5353 -v

Sat Jun 20 20:22:48 2015 request 12.17.168.192.in-addr.arpa
Sat Jun 20 20:22:48 2015 response 12.17.168.192.in-addr.arpa from 114.114.115.115:53 - filter
Sat Jun 20 20:22:48 2015 response 12.17.168.192.in-addr.arpa from 114.114.114.114:53 - filter
Sat Jun 20 20:22:48 2015 response 12.17.168.192.in-addr.arpa from 8.8.4.4:53 - pass
Sat Jun 20 20:22:48 2015 response 12.17.168.192.in-addr.arpa from 8.8.8.8:53 - pass
Sat Jun 20 20:22:48 2015 request facebook.com
Sat Jun 20 20:22:48 2015 response facebook.com from 114.114.115.115:53 - 203.98.7.65, filter
Sat Jun 20 20:22:48 2015 response facebook.com from 114.114.114.114:53 - 203.98.7.65, filter
Sat Jun 20 20:22:48 2015 response 12.17.168.192.in-addr.arpa from 208.67.222.222:443 - pass
Sat Jun 20 20:22:48 2015 response 12.17.168.192.in-addr.arpa from 208.67.222.222:5353 - pass
Sat Jun 20 20:22:48 2015 response facebook.com from 8.8.4.4:53 - 173.252.120.6, pass
Sat Jun 20 20:22:48 2015 response facebook.com from 8.8.8.8:53 - 173.252.120.6, pass
Sat Jun 20 20:22:48 2015 request facebook.com
Sat Jun 20 20:22:48 2015 response facebook.com from 114.114.114.114:53 - filter
Sat Jun 20 20:22:48 2015 response facebook.com from 114.114.115.115:53 - filter
Sat Jun 20 20:22:49 2015 response facebook.com from 208.67.222.222:443 - 173.252.120.6, pass
Sat Jun 20 20:22:49 2015 response facebook.com from 208.67.222.222:5353 - 173.252.120.6, pass
Sat Jun 20 20:22:49 2015 response facebook.com from 8.8.4.4:53 - pass
Sat Jun 20 20:22:49 2015 response facebook.com from 8.8.8.8:53 - pass
Sat Jun 20 20:22:49 2015 response facebook.com from 208.67.222.222:443 - pass
Sat Jun 20 20:22:49 2015 response facebook.com from 208.67.222.222:5353 - pass

VPN断开后的log：

Sat Jun 20 20:23:31 2015 request 12.17.168.192.in-addr.arpa
Sat Jun 20 20:23:31 2015 response 12.17.168.192.in-addr.arpa from 114.114.115.115:53 - filter
Sat Jun 20 20:23:31 2015 response 12.17.168.192.in-addr.arpa from 114.114.114.114:53 - filter
Sat Jun 20 20:23:31 2015 response 12.17.168.192.in-addr.arpa from 208.67.222.222:443 - pass
Sat Jun 20 20:23:31 2015 request facebook.com
Sat Jun 20 20:23:31 2015 response facebook.com from 114.114.115.115:53 - 203.98.7.65, filter
Sat Jun 20 20:23:31 2015 response facebook.com from 114.114.114.114:53 - 203.98.7.65, filter
Sat Jun 20 20:23:31 2015 response facebook.com from 208.67.222.222:443 - 173.252.120.6, pass
Sat Jun 20 20:23:31 2015 response 12.17.168.192.in-addr.arpa from 208.67.222.222:5353 - pass
Sat Jun 20 20:23:31 2015 request facebook.com
Sat Jun 20 20:23:31 2015 response facebook.com from 114.114.114.114:53 - filter
Sat Jun 20 20:23:31 2015 response facebook.com from 114.114.115.115:53 - filter
Sat Jun 20 20:23:31 2015 response facebook.com from 208.67.222.222:5353 - 173.252.120.6, pass
Sat Jun 20 20:23:31 2015 response facebook.com from 208.67.222.222:5353 - pass

VPN重连后的log：

Sat Jun 20 20:24:26 2015 request 12.17.168.192.in-addr.arpa
Sat Jun 20 20:24:26 2015 response 12.17.168.192.in-addr.arpa from 114.114.114.114:53 - filter
Sat Jun 20 20:24:26 2015 response 12.17.168.192.in-addr.arpa from 114.114.115.115:53 - filter
Sat Jun 20 20:24:28 2015 request facebook.com
Sat Jun 20 20:24:28 2015 response facebook.com from 114.114.114.114:53 - 203.98.7.65, filter
Sat Jun 20 20:24:28 2015 response facebook.com from 114.114.115.115:53 - 203.98.7.65, filter
Sat Jun 20 20:24:30 2015 request facebook.com
Sat Jun 20 20:24:30 2015 response facebook.com from 114.114.114.114:53 - filter
Sat Jun 20 20:24:30 2015 response facebook.com from 114.114.115.115:53 - filter
Sat Jun 20 20:24:32 2015 request facebook.com
Sat Jun 20 20:24:32 2015 response facebook.com from 114.114.115.115:53 - 203.98.7.65, filter
Sat Jun 20 20:24:32 2015 response facebook.com from 114.114.114.114:53 - 203.98.7.65, filter
Sat Jun 20 20:24:34 2015 request facebook.com
Sat Jun 20 20:24:34 2015 response facebook.com from 114.114.114.114:53 - filter
Sat Jun 20 20:24:34 2015 response facebook.com from 114.114.115.115:53 - filter

**Comment by clowwindy** [comment]
请检查你的 VPN 设置。
