### ISSUE TITLE
编译OpenWRT x86平台的时候报错undefined reference to `MAX'

### ISSUE THREAD

**Issue by zhaozhongyao** [clowwindy/ChinaDNS#115]
chinadns.o: In function `main':
chinadns.c:(.text.startup+0xcf0): undefined reference to `MAX'
collect2: error: ld returned 1 exit status
make[5]: *** [chinadns] Error 1
make[5]: Leaving directory `/home/build/openwrt/build_dir/target-i386_i486_musl-1.1.10/ChinaDNS-/chinadns-1.3.1/src'
make[4]: *** [all-recursive] Error 1
make[4]: Leaving directory `/home/build/openwrt/build_dir/target-i386_i486_musl-1.1.10/ChinaDNS-/chinadns-1.3.1'
make[3]: *** [all] Error 2
make[3]: Leaving directory `/home/build/openwrt/build_dir/target-i386_i486_musl-1.1.10/ChinaDNS-/chinadns-1.3.1'
make[2]: *** [/home/build/openwrt/build_dir/target-i386_i486_musl-1.1.10/ChinaDNS-/chinadns-1.3.1/.built] Error 2
make[2]: Leaving directory `/home/build/openwrt/package/ChinaDNS/openwrt'
make[1]: *** [package/ChinaDNS/openwrt/compile] Error 2
make[1]: Leaving directory `/home/build/openwrt'
make: *** [package/ChinaDNS/openwrt/compile] Error 2

**Comment by clowwindy** [comment]
Please try master code.
