### ISSUE TITLE
在查询同时包含国内和国外的IP的DNS纪录时无法得到结果

### ISSUE THREAD

**Issue by living42** [clowwindy/ChinaDNS#118]
在开启双向过滤(-d)的的情况下，国内DNS的结果会过滤掉不是国内地址的的包，而国外DNS则相反。

如果我的理解没错的话，如果出现返回结果大于两个IP的，而且结果中同时包含有国内和国外的的IP时，会有下面两种结果：

+ 结果来自国内DNS，而结果中包含国外IP，被过滤
+ 结果来自国外DNS，而结果中包含国内IP，被过滤

从而导致这类查询没有返回结果。

举个例子 www.acfun.tv (203.130.60.32, 70.39.191.159)

日志如下：

    $ chinadns -d -p 5533 -c raw.txt -v   
    Mon Aug 10 04:16:12 2015 request www.acfun.tv
    Mon Aug 10 04:16:12 2015 response www.acfun.tv from 223.5.5.5:53 - 203.130.60.32, 70.39.191.159, filter
    Mon Aug 10 04:16:12 2015 response www.acfun.tv from 114.114.114.114:53 - 70.39.191.159, filter
    Mon Aug 10 04:16:12 2015 response www.acfun.tv from 208.67.222.222:5353 - 203.130.60.32, filter
    Mon Aug 10 04:16:13 2015 response www.acfun.tv from 8.8.8.8:53 - 70.39.191.159, 203.130.60.32, filter
    Mon Aug 10 04:16:13 2015 response www.acfun.tv from 208.67.222.222:443 - 203.130.60.32, filter

**Comment by clowwindy** [comment]
不要开启双向过滤，这个功能是为一个网络特殊的用户特别设计的。
