### ISSUE TITLE
Running is not stable in OS X

### ISSUE THREAD

**Issue by gino2010** [clowwindy/ChinaDNS#49]
I just run this tool in OS X
I found it is not stable. Detail:
When I ran it at first time, I can visit google and youtube smoothly.
But after a few minutes, I restarted it, I can't visit google and youtube any more. It didn't seem to work.
I ran it in verbose logging mode, but when I request www.google.com site in chrome, nothing is outputted
When I nslookup www.google.com, it will output some request log.

Do you meet same problem in Linux system? Or this problem is only for Mac OS X?

**Comment by clowwindy** [comment]
I guess it's the DNS cache of the OS or something but I'm not sure. I only use ChinaDNS on OpenWRT.

Please note using this tool solely won't help you load Google. You need proxy or VPN.

**Comment by gino2010** [comment]
I see. Thanks
