### ISSUE TITLE
weibo.com 返回的IP是国外的（HK）

### ISSUE THREAD

**Issue by myliyifei** [clowwindy/ChinaDNS#53]
配置如下，国外的DNS由日本的VPS进行了UDP中转。我到VPS的ping值大约70ms
开启了双向解析
延迟部分测试了200 300 400MS,都没有用。

# cat /etc/config/chinadns 

config chinadns
        option enable '1'
        option bidirectional '1'
        option iplist '/etc/chinadns_iplist.txt'
        option chnroute '/etc/chinadns_chnroute.txt'
        option port '5301'
        option server '114.114.114.114,127.0.0.1:5353'
        option result_delay '0.4'

# dig weibo.com @127.0.0.1 -p 5301

; <<>> DiG 9.9.1-P3 <<>> weibo.com @127.0.0.1 -p 5301
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 42209
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;weibo.com.                     IN      A

;; ANSWER SECTION:
weibo.com.              14      IN      A       114.134.80.162

;; Query time: 472 msec
;; SERVER: 127.0.0.1#5301(127.0.0.1)
;; WHEN: Wed Jan 21 11:16:46 2015
;; MSG SIZE  rcvd: 54

**Comment by hgl** [comment]
直接本地查询114返回的ip是什么？在chnroute.txt列举的ip范围内吗？

**Comment by clowwindy** [comment]
尝试更新到 1.3 然后启用压缩指针功能

**Comment by msxcms** [comment]
我这里使用压缩指针后没有问题了

**Comment by myliyifei** [comment]
我关闭了双向解析好像也没有问题了。困惑点：1 是否还需要关闭双向解析 2 如果国外的DNS走VPS，还是否需要开启压缩指针

2015-01-27 16:03 GMT+08:00 clowwindy <notifications@github.com>:

**Comment by msxcms** [comment]
发现个问题，使用 -m 之后，解析国外域名的时候，dig的时候返回很快，但是ping却要很久（10秒以上），比如 www.hostloc.com。

**Comment by sdysj** [comment]
对，我也发现了，还有一个有趣的现象是在 OpenWRT 里用 resolveip 除了 google.com 能返回，其他都不能。

**Comment by xcjiang** [comment]
bidirectional 貌似不能开，开了出一些奇怪的问题，比如我手机上的几个腾讯手游，开了bidirectional 之后就死活连不上，关掉之后就马上正常了。
