### ISSUE TITLE
ChinaDNS 应该有个打印版本号的功能

### ISSUE THREAD

**Issue by shiny** [clowwindy/ChinaDNS#55]
目前无论是 `chinadns -h` 还是 `chinadns -v` 都看不到当前使用的版本号。 或者能不能像 python 这样，
`python -v` 是 verbose，`python -V` 是 print the Python version number

打印版本号可以帮助确定当前版本是否低于最新版。

**Comment by clowwindy** [comment]
运行时会打印版本号

**Comment by shiny** [comment]
但是很不方便，用  `/etc/init.d/chinadns start` 没有打印内容， `/var/log/chinadns.log` 也是空的。

**Comment by clowwindy** [comment]
chinadns -p 12345

**Comment by myliyifei** [comment]
虽然这个功能是有的，但是跟大家用linux的习惯不太一样
