### ISSUE TITLE
希望尽早补完queue独立ID的逻辑

### ISSUE THREAD

**Issue by gmsj0001** [clowwindy/ChinaDNS#56]
第一次试用这个软件，nslookup各种超时，换了好几个版本，还以为是重大bug，后来读了代码才发现queue那里的todo。
个人感觉独立id并不麻烦，应该可以直接用queue数组的下标作为远程查询的id，查找也不用再去循环一次了。

**Comment by clowwindy** [comment]
建议你先确定超时是这个原因导致的，因为我从来没有遇到类似的现象。

**Comment by gmsj0001** [comment]
windows系统会使用随机请求id，所以不影响正常使用。但nslookup命令每次均使用1、2、3这样的固定id，在当前的queue_lookup逻辑下只有第一次是正确的，第二次以后就会超时失败（解析结果被发送到第一次查询用过的端口）。
windows下使用nslookup命令可重现此故障。

**Comment by Pentiumluyu** [comment]
我觉得可以参考dnsmasq的方法
https://github.com/guns/dnsmasq/blob/nerv/src/forward.c#L335

**Comment by clowwindy** [comment]
1. 如果我们要自己随机生成 id，应该随机生成，而不应该递增，主要是安全方面的原因，具体可以读一下 bind 源码里的相关注释
2. 如果要 scalable，一个方法是用 hash table，把 question section 当 key，(原 id，新 id) 作为 value，这样返回 response 的时候可以直接查出 (原 id，新 id) ，验证新 id 匹配后，把原 id 替换到 response 里，这样并发数不受 65536 限制。不过我觉得，家用路由器上还是算了吧
3. dnsmasq 的方法看起来比较挫，但是在这个场景下可以用

**Comment by gmsj0001** [comment]
1、随机还是递增在此场景下似乎影响不大，只是唯一id生成实现的方案选择，只是复杂性和性能的问题，选哪个看喜好了。递增编码简单，当前项目改动应该不超过10行，随机要跑循环或者上hash表。
2、用question当key玩大了（疑问：是否符合协议规范？），dns并发到65536估计路由器早被玩坏了。还是源ip、源端口、源id三个参数标识一个查询的唯一性比较科学。本项目定位只是dns转发而不是缓存服务器，且对外使用固定端口，也就是只要做到唯一id反向对应到客户端的三个参数就够了。
