### ISSUE TITLE
在Mint 17.1上面编译无法通过怎么破

### ISSUE THREAD

**Issue by tony1016** [clowwindy/ChinaDNS#60]
控制台输出
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/home/tony/下载/chinadns-1.3.0':
configure: error: C compiler cannot create executables
See `config.log' for more details

查看config.log发现如下
gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) 
configure:3196: $? = 0
configure:3185: gcc -V >&5
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:3196: $? = 4
configure:3185: gcc -qversion >&5
gcc: error: unrecognized command line option '-qversion'
gcc: fatal error: no input files
compilation terminated.
configure:3196: $? = 4
configure:3216: checking whether the C compiler works
configure:3238: gcc    conftest.c  >&5
/usr/bin/ld: cannot find crt1.o: No such file or directory
/usr/bin/ld: cannot find crti.o: No such file or directory
/usr/bin/ld: cannot find -lc
/usr/bin/ld: cannot find crtn.o: No such file or directory
collect2: error: ld returned 1 exit status
configure:3242: $? = 1
configure:3280: result: no
configure: failed program was:
| /* confdefs.h */

**Comment by clowwindy** [comment]
Seems your compiler doesn't work at all.

**Comment by tony1016** [comment]
@clowwindy  原因查明，确实是因为没有安装build-essential，但是还是建议放到readme.md的linux编译一节，给新人以提醒，仅仅是个建议。

**Comment by clowwindy** [comment]
We don't teach basic Linux in Installation Guides. [OpenVPN](https://github.com/OpenVPN/openvpn) doesn't, either. Neither does [nginx](http://nginx.org/en/docs/configure.html).
