### ISSUE TITLE
fake dns ip 一直在增加

### ISSUE THREAD

**Issue by scola** [clowwindy/ChinaDNS#62]
fake dns ip 一直在增加， 导致某些ip过滤不了， 自己手动更新过那个iplist.txt， 但是增加太快。现在只能VPN 或者 ss-tunnel 解决 DNS 污染问题。刚刚尝试了最新版本 1.3.0 ，debian6.0下编译测试（长城宽带）如下：
scola@debian:~/tmp/chinadns-1.3.0$ src/chinadns -m -c chnroute.txt -p 5300 -v
ChinaDNS 1.3.0
Sun Feb  1 19:30:27 2015 request facebook.com
Sun Feb  1 19:30:27 2015 response facebook.com from 8.8.8.8:53 - 79.143.84.11, pass
Sun Feb  1 19:30:27 2015 response facebook.com from 8.8.4.4:53 - 49.212.182.33, pass
Sun Feb  1 19:30:27 2015 response facebook.com from 114.114.114.114:53 - 210.129.90.38, filter
Sun Feb  1 19:30:27 2015 response facebook.com from 223.5.5.5:53 - 195.27.70.185, filter
Sun Feb  1 19:31:25 2015 request twitter.com
Sun Feb  1 19:31:25 2015 response twitter.com from 8.8.4.4:53 - 50.97.235.132, pass
Sun Feb  1 19:31:25 2015 response twitter.com from 8.8.8.8:53 - 50.97.235.132, pass
Sun Feb  1 19:31:25 2015 response twitter.com from 114.114.114.114:53 - 50.22.67.221, filter
Sun Feb  1 19:31:25 2015 response twitter.com from 223.5.5.5:53 - 199.19.205.203, filter
Sun Feb  1 19:32:24 2015 request dropbox.com
Sun Feb  1 19:32:24 2015 response dropbox.com from 8.8.4.4:53 - 64.135.82.110, pass
Sun Feb  1 19:32:24 2015 response dropbox.com from 8.8.8.8:53 - 180.235.150.28, pass
Sun Feb  1 19:32:24 2015 response dropbox.com from 114.114.114.114:53 - 64.68.198.1, filter
Sun Feb  1 19:32:24 2015 response dropbox.com from 223.5.5.5:53 - 37.228.88.146, filter
===================================================
scola@debian:~$ dig @127.0.0.1 -p 5300 facebook.com

; <<>> DiG 9.7.3 <<>> @127.0.0.1 -p 5300 facebook.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 19568
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 2, ADDITIONAL: 2

;; QUESTION SECTION:
;facebook.com.			IN	A

这种问题是不是只能通过更新 iplist.txt 解决？

**Comment by scola** [comment]
scola@debian:~$ dig @127.0.0.1 -p 5300 facebook.com

; <<>> DiG 9.7.3 <<>> @127.0.0.1 -p 5300 facebook.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 19568
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 2, ADDITIONAL: 2

;; QUESTION SECTION:
;facebook.com.			IN	A

;; ANSWER SECTION:
facebook.com.		61	IN	A	79.143.84.11

;; AUTHORITY SECTION:
facebook.com.		53236	IN	NS	b.ns.facebook.com.
facebook.com.		53236	IN	NS	a.ns.facebook.com.

;; ADDITIONAL SECTION:
a.ns.facebook.com.	168	IN	A	27.102.212.8
b.ns.facebook.com.	9	IN	A	178.162.214.73

;; Query time: 14 msec
;; SERVER: 127.0.0.1#5300(127.0.0.1)
;; WHEN: Sun Feb  1 19:30:27 2015
;; MSG SIZE  rcvd: 113

scola@debian:~$ dig @127.0.0.1 -p 5300 twitter.com

; <<>> DiG 9.7.3 <<>> @127.0.0.1 -p 5300 twitter.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 27077
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 4, ADDITIONAL: 4

;; QUESTION SECTION:
;twitter.com.			IN	A

;; ANSWER SECTION:
twitter.com.		294	IN	A	50.97.235.132

;; AUTHORITY SECTION:
twitter.com.		159461	IN	NS	ns3.p34.dynect.net.
twitter.com.		159461	IN	NS	ns2.p34.dynect.net.
twitter.com.		159461	IN	NS	ns4.p34.dynect.net.
twitter.com.		159461	IN	NS	ns1.p34.dynect.net.

;; ADDITIONAL SECTION:
ns1.p34.dynect.net.	54899	IN	A	208.78.70.34
ns2.p34.dynect.net.	54899	IN	A	204.13.250.34
ns3.p34.dynect.net.	54899	IN	A	208.78.71.34
ns4.p34.dynect.net.	54899	IN	A	204.13.251.34

;; Query time: 10 msec
;; SERVER: 127.0.0.1#5300(127.0.0.1)
;; WHEN: Sun Feb  1 19:31:25 2015
;; MSG SIZE  rcvd: 195

scola@debian:~$ dig @127.0.0.1 -p 5300 dropbox.com

; <<>> DiG 9.7.3 <<>> @127.0.0.1 -p 5300 dropbox.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 4810
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 4, ADDITIONAL: 4

;; QUESTION SECTION:
;dropbox.com.			IN	A

;; ANSWER SECTION:
dropbox.com.		2260	IN	A	64.135.82.110

;; AUTHORITY SECTION:
dropbox.com.		54696	IN	NS	ns-1949.awsdns-51.co.uk.
dropbox.com.		54696	IN	NS	ns-564.awsdns-06.net.
dropbox.com.		54696	IN	NS	ns-315.awsdns-39.com.
dropbox.com.		54696	IN	NS	ns-1162.awsdns-17.org.

;; ADDITIONAL SECTION:
ns-315.awsdns-39.com.	54629	IN	A	205.251.193.59
ns-564.awsdns-06.net.	54696	IN	A	205.251.194.52
ns-1162.awsdns-17.org.	54629	IN	A	205.251.196.138
ns-1949.awsdns-51.co.uk. 54697	IN	A	205.251.199.157

;; Query time: 23 msec
;; SERVER: 127.0.0.1#5300(127.0.0.1)
;; WHEN: Sun Feb  1 19:32:24 2015
;; MSG SIZE  rcvd: 246

**Comment by cokebar** [comment]
早就这样了。。 已经换了策略了 请尝试开启压缩指针

**Comment by scola** [comment]
@cokebar  
scola@debian:~/tmp/chinadns-1.3.0$ src/chinadns -m -c chnroute.txt -p 5300 -v
-m 不就是已经开启了么

**Comment by cokebar** [comment]
抱歉没看清 不过开启-m以后 就不管iplist了
再尝试访问一下 你这个结果貌似没有问题啊 你每次的结果都不一样么？
还有就是 最好还是国外DNS让VPS转发这样国外解析是就近于VPS的 否则是就近与你自己，这样可能造成VPS反而无法访问 或者访问缓慢

**Comment by scola** [comment]
@cokebar  
结果没有问题么, twitter的 查出的 IP 是 50.97.235.132 ? 也是twitter的 IP?
我记得正确的 都是 199.x.x.x 这样的

**Comment by cokebar** [comment]
@scola 确实不对 看-v的结果 -m貌似也没起到效果啊 我这里有这么一行：Mon Feb  2 10:23:53 2015 chinadns.c:650 ns_initparse: Message too long
难道长宽有自己一套污染方案？

**Comment by scola** [comment]
我是用 https://github.com/clowwindy/ChinaDNS/releases 
1.3.0 测试的, 是否需要 clone 最新版测试

**Comment by clowwindy** [comment]
不支持长城宽带。

**Comment by scola** [comment]
经过一番测试发现我这 google dns 被劫持， 但是 opendns 正常， 所以我在代码里去掉了google dns解决了 DNS 污染问题， opendns 有点慢我也认了，结果完全正确，谢谢作者 @clowwindy 和 @cokebar 的帮助
https://github.com/scola/ChinaDNS/commit/21c4d32e53014e0bcc5f5c6bff62801ab04f0073

**Comment by clowwindy** [comment]
DNS 服务器可以用 -s 参数指定。

**Comment by scola** [comment]
谢谢提示，没仔细看usage, 这下更方便了

**Comment by airystar** [comment]
长宽的8.8.8.8可能是钓鱼主机，看：
traceroute to 8.8.8.8 (8.8.8.8), 30 hops max, 60 byte packets
 1  gateway (192.168.1.1)  1.809 ms  3.605 ms  5.109 ms
 2  101.245.4.1 (101.245.4.1)  81.571 ms  81.575 ms  81.544 ms
 3  10.64.129.206 (10.64.129.206)  8.761 ms  9.344 ms  10.734 ms
 4  * * *
 5  google-public-dns-a.google.com (8.8.8.8)  9.818 ms  11.825 ms  10.924 ms
根本没有到外网。

**Comment by beterhans** [comment]
曾经的长宽用户表示 就是钓鱼
    
    
    On 5/17/15 6:24 PM, airy wrote:
    
    
      长宽的8.8.8.8可能是钓鱼主机，看：
        traceroute to 8.8.8.8 (8.8.8.8), 30 hops max, 60 byte packets
        1 gateway (192.168.1.1) 1.809 ms 3.605 ms 5.109 ms
        2 101.245.4.1 (101.245.4.1) 81.571 ms 81.575 ms 81.544 ms
        3 10.64.129.206 (10.64.129.206) 8.761 ms 9.344 ms 10.734 ms
        4 * * *
        5 google-public-dns-a.google.com (8.8.8.8) 9.818 ms 11.825 ms
        10.924 ms
        根本没有到外网。
      —
        Reply to this email directly or view
          it on GitHub.
