### ISSUE TITLE
Problem when delay time set to zero

### ISSUE THREAD

**Issue by cokebar** [clowwindy/ChinaDNS#63]
国内使用ISP的DNS 国外使用自己搭建的远程非标DNS转发器
ISP的DNS不太好，一些国外域名解析失败；国外自己搭的正常
由于我这种方式没有DNS污染所以我把延迟时间设置成0了 不过此时会导致ChinaDNS将结果全部抛弃。
等待时间改成0.1后现象消失。
能否重定义一下等待时间为0时候的行为？ 既然设置为0 应该就是没有DNS污染时候才这样设置，此时不应该抛弃国外结果。或者说 定义等待时间不能为0，然后不需要等待时间的时候，去掉-y
@aa65535 能否改下你的luci-app 把等待时间也加个开关

**Comment by clowwindy** [comment]
国内 DNS 会被污染，不能这样用

**Comment by aa65535** [comment]
去掉 -y 参数也会有默认的 0.3，另外 Luci 中留空的话是不会加这个参数的。

**Comment by cokebar** [comment]
我改成0.1好了 不知道还会有这个问题 我说怎么好多人给我反应用了ss-tunnel还污染呢。。

**Comment by LazyZhu** [comment]
现在指针也有delay了, 得加 -y 0.1

**Comment by aa65535** [comment]
实际情况是开启压缩指针后 should_filter_query 不会返回 -1， 也就不会出现 delay 了。

**Comment by LazyZhu** [comment]
@aa65535 原来如此.
chinadns 不支持TCP和缓存,  如果能在pdnsd打个patch来实现指针就就好了

**Comment by clowwindy** [comment]
@LazyZhu 
pdnsd 不能根据线路优化结果。

**Comment by LazyZhu** [comment]
@clowwindy 
pdnsd 有个par_queries参数,允许分批查询, 以前就是reject配合fakeip列表,设置国内和tunnel两个server,设置 par_queries=1,后 先查询国内域名列表,遇到fakeip丢弃,启用tunnel查询.
当然现在无效了,但可以添加的accept功能(相对与reject),只要含有chnroute的通过,否则启用tunnel,这样不会有国内CDN问题
http://members.home.nl/p.a.rombouts/pdnsd/doc.html

**Comment by aa65535** [comment]
如果随机 IP 中有 chn ip 的话，accept 功能就不能用了。

**Comment by clowwindy** [comment]
@LazyZhu 也是个办法，但是因为有个先后顺序，查询国外效果和 delay 是一样的，甚至更慢一点。

**Comment by LazyZhu** [comment]
Done with https://gist.github.com/LazyZhu/3f0ad3ec6bbd86748897
Add a line `accept=/path/to/chroute.list;` to the server section of pdnsd.conf.
Same to reject, accept also has `accept_policy` and `accept_recursively` options.

**Comment by Phishion** [comment]
我发现了一个奇怪的现象，我这边设置114.114.114.114+8.8.8.8的时候，dig淘宝网知道取用国内的地址，设置成114.114.114.114+127.0.0.1:5353（pdnsd）的时候，优先取用的是pdnsd返回的国外地址，为什么会有这样的情况？

**Comment by Phishion** [comment]
不能发布消息了？
