### ISSUE TITLE
Segmentation fault when loaded by OpenWRT init script.

### ISSUE THREAD

**Issue by Koishi-komeiji** [clowwindy/ChinaDNS#69]
After OpenWRT starts, There's no process of ChinaDNS. However, later it can be start manually.  
I tried to redirect the error outputs to file, in which I saw it said "Segmentation Fault".
I didn't modify anything before, it's run on a totally fresh system environment. I think it may be a bug in the init script. Please inspect this.

**Comment by heiybb** [comment]
Maybe something wrong with your Openwrt or router's hardware, I used to meet thr same problem but I simply  flash another openwrt image,  then it disappear.
Though I haven't redirect any error details:)

**Comment by clowwindy** [comment]
Use strace to trace system calls or generate a core dump file.
