### ISSUE TITLE
ChinaDNS listens to 0.0.0.0 by default, which includes the WAN interface

### ISSUE THREAD

**Issue by mclee** [clowwindy/ChinaDNS#70]
If the router has a public accessible IP, then the ChinaDNS server will be open for probing. Will you consider implementing something like "--local-service" that [dnsmasq](http://www.thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html) does?

It seems like by enabling this dnsmasq will only answer DNS queries from hosts whose address is on a local subnet.

**Comment by Pentiumluyu** [comment]
Use option -b to specify the binding address.

**Comment by mclee** [comment]
@Pentiumluyu  You probably didn't get my point. Take dnsmasq for example. It already has options like -a or -z to specify the address / interface. But by providing an option --local-service, default installs can be rest assured without knowing specifically which addresses or interface the user will be using for local queries.

Of course it's only a suggestion, but I think it's something worth mentioning.

**Comment by clowwindy** [comment]
Currently we only offer packages for OpenWRT, which has a default reject rule on its wan interface.
