### ISSUE TITLE
 ns_initparse: Message too long

### ISSUE THREAD

**Issue by ivyswen** [clowwindy/ChinaDNS#71]
我用chinadns做dnsmasq的上游DNS服务器，我在电脑上nslookup一个不存在的域名，后台的会有报错日志：chinadns.c:650 ns_initparse: Message too long
还有一种报错chinadns.c:577 ns_initparse: Message too long，我不确定是什么原因产生的。

**Comment by Pentiumluyu** [comment]
使用DNS Pointer Mutation之后出现的，DNS返回的第一个结果可能会是这样，你可以抓包看看。（ps: 不影响使用）
