### ISSUE TITLE
Missing configure file

### ISSUE THREAD

**Issue by jchia** [clowwindy/ChinaDNS#79]
The Linux installation instructions require a file 'configure' but it's not in the repo. Either it is missing from the repo or the instructions for generating it are missing.

**Comment by jchia** [comment]
I think the Linux build steps are missing "autoreconf -i".

**Comment by clowwindy** [comment]
- Linux / Unix

  ***Download a release.***

      ./configure && make
      src/chinadns -m -c chnroute.txt
