### ISSUE TITLE
能不能增加对socks/ss的支持？

### ISSUE THREAD

**Issue by ownhere** [clowwindy/ChinaDNS#81]
“因为有些运营商会屏蔽正确结果，所以虽然伪造包被过滤了，但是正确包永远也不会到达“
对于上述情况，能否增加一个附加查询能力支持，就是允许用户配置一个socks/ss代理（其实用到chinadns项目的用户基本都有这类代理），当某次域名查询发现被污染的时候，不需要等待正确结果，而是直接再次通过socks/ss发起另一次查询请求，这样就可以更好的兼顾各种网络情况了

**Comment by clowwindy** [comment]
Please search Google or ask in the forums how to do it.

**Comment by ownhere** [comment]
嗯，用1.3.1编译了一下貌似满足我的需求了，之前使用别人编译的1.2.x还不行。
附上我对代码中与ns_parser有关的代码的本地化处理，不需要再依赖libresolv了，动态链接版编译后大概31k大小。可以在entware,optware等uclibc版本低于0.9.33的系统上编译。

**Comment by kdrx** [comment]
能否分享下这个可以在上编译的源码？

**Comment by ownhere** [comment]
@kdrx ，已经提交了pull request
