### ISSUE TITLE
OpenWrt x86 版本的编译版本支持

### ISSUE THREAD

**Issue by sxp** [clowwindy/ChinaDNS#89]
目前使用的 OpenWrt 是 x86 版本的，希望可以有编译好的包支持

**Comment by kdrx** [comment]
http://sourceforge.net/projects/openwrt-dist/files/chinadns/1.3.1-4f2692e/ChinaDNS_1.3.1-1_x86.ipk

**Comment by sxp** [comment]
感谢，我试试
