### ISSUE TITLE
关于超时的建议　

### ISSUE THREAD

**Issue by JoveYu** [clowwindy/ChinaDNS#90]
chinaDNS非常实用　　但是在使用过程中　我遇到这样一个问题　　当ｖｐｎ断开的时候　　国外ｄｎｓ无法解析　　国外域名无法访问　　一直提示在解析域名　　我觉得如果添加一个国外ｄｎｓ超时时间  当过了  就返回国内dns的解析  这样会好分多

**Comment by clowwindy** [comment]
就是故意设计成宁可没有也不要污染，因为下游会缓存错误结果。
