### ISSUE TITLE
musl libc

### ISSUE THREAD

**Issue by leenchan** [clowwindy/ChinaDNS#99]
OpenWrt trunk 45995 's default libc changed ( uclibc > musl libc )

Make chinadns
make: Entering directory `/home/leenchan/Desktop/openwrt'
make[1]: Entering directory `/home/leenchan/Desktop/openwrt'
make[2]: Entering directory `/home/leenchan/Desktop/openwrt'
make[2]: Leaving directory `/home/leenchan/Desktop/openwrt'
make[1]: Leaving directory `/home/leenchan/Desktop/openwrt'
make[1]: Entering directory `/home/leenchan/Desktop/openwrt'
make[2]: Entering directory `/home/leenchan/Desktop/openwrt/package/libs/toolchain'
if [ -f /home/leenchan/Desktop/openwrt/staging_dir/target-mips_34kc_musl-1.1.10/pkginfo/toolchain.default.install.clean ]; then rm -f /home/leenchan/Desktop/openwrt/staging_dir/target-mips_34kc_musl-1.1.10/pkginfo/toolchain.default.install /home/leenchan/Desktop/openwrt/staging_dir/target-mips_34kc_musl-1.1.10/pkginfo/toolchain.default.install.clean; fi; echo "libc" >> /home/leenchan/Desktop/openwrt/staging_dir/target-mips_34kc_musl-1.1.10/pkginfo/toolchain.default.install
if [ -f /home/leenchan/Desktop/openwrt/staging_dir/target-mips_34kc_musl-1.1.10/pkginfo/toolchain.default.install.clean ]; then rm -f /home/leenchan/Desktop/openwrt/staging_dir/target-mips_34kc_musl-1.1.10/pkginfo/toolchain.default.install /home/leenchan/Desktop/openwrt/staging_dir/target-mips_34kc_musl-1.1.10/pkginfo/toolchain.default.install.clean; fi; echo "libgcc" >> /home/leenchan/Desktop/openwrt/staging_dir/target-mips_34kc_musl-1.1.10/pkginfo/toolchain.default.install
if [ -f /home/leenchan/Desktop/openwrt/staging_dir/target-mips_34kc_musl-1.1.10/pkginfo/toolchain.default.install.clean ]; then rm -f /home/leenchan/Desktop/openwrt/staging_dir/target-mips_34kc_musl-1.1.10/pkginfo/toolchain.default.install /home/leenchan/Desktop/openwrt/staging_dir/target-mips_34kc_musl-1.1.10/pkginfo/toolchain.default.install.clean; fi; echo "libstdcpp" >> /home/leenchan/Desktop/openwrt/staging_dir/target-mips_34kc_musl-1.1.10/pkginfo/toolchain.default.install
if [ -f /home/leenchan/Desktop/openwrt/staging_dir/target-mips_34kc_musl-1.1.10/pkginfo/toolchain.default.install.clean ]; then rm -f /home/leenchan/Desktop/openwrt/staging_dir/target-mips_34kc_musl-1.1.10/pkginfo/toolchain.default.install /home/leenchan/Desktop/openwrt/staging_dir/target-mips_34kc_musl-1.1.10/pkginfo/toolchain.default.install.clean; fi; echo "libpthread" >> /home/leenchan/Desktop/openwrt/staging_dir/target-mips_34kc_musl-1.1.10/pkginfo/toolchain.default.install
if [ -f /home/leenchan/Desktop/openwrt/staging_dir/target-mips_34kc_musl-1.1.10/pkginfo/toolchain.default.install.clean ]; then rm -f /home/leenchan/Desktop/openwrt/staging_dir/target-mips_34kc_musl-1.1.10/pkginfo/toolchain.default.install /home/leenchan/Desktop/openwrt/staging_dir/target-mips_34kc_musl-1.1.10/pkginfo/toolchain.default.install.clean; fi; echo "librt" >> /home/leenchan/Desktop/openwrt/staging_dir/target-mips_34kc_musl-1.1.10/pkginfo/toolchain.default.install
make[2]: Leaving directory `/home/leenchan/Desktop/openwrt/package/libs/toolchain'
make[2]: Entering directory `/home/leenchan/Desktop/openwrt/feeds/leenchan/chinadns'
CFLAGS="-Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float -Wformat -Werror=format-security -Wl,-z,now -Wl,-z,relro  -I/home/leenchan/Desktop/openwrt/staging_dir/target-mips_34kc_musl-1.1.10/usr/include -I/home/leenchan/Desktop/openwrt/staging_dir/target-mips_34kc_musl-1.1.10/include -I/home/leenchan/Desktop/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.10/usr/include -I/home/leenchan/Desktop/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.10/include " CXXFLAGS="-Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float -Wformat -Werror=format-security -Wl,-z,now -Wl,-z,relro  -I/home/leenchan/Desktop/openwrt/staging_dir/target-mips_34kc_musl-1.1.10/usr/include -I/home/leenchan/Desktop/openwrt/staging_dir/target-mips_34kc_musl-1.1.10/include -I/home/leenchan/Desktop/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.10/usr/include -I/home/leenchan/Desktop/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.10/include " LDFLAGS="-L/home/leenchan/Desktop/openwrt/staging_dir/target-mips_34kc_musl-1.1.10/usr/lib -L/home/leenchan/Desktop/openwrt/staging_dir/target-mips_34kc_musl-1.1.10/lib -L/home/leenchan/Desktop/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.10/usr/lib -L/home/leenchan/Desktop/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.10/lib " make   -C /home/leenchan/Desktop/openwrt/build_dir/target-mips_34kc_musl-1.1.10/chinadns-1.3.1/. AR="mips-openwrt-linux-musl-gcc-ar" AS="mips-openwrt-linux-musl-gcc -c -Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float -Wformat -Werror=format-security -Wl,-z,now -Wl,-z,relro" LD=mips-openwrt-linux-musl-ld NM="mips-openwrt-linux-musl-gcc-nm" CC="mips-openwrt-linux-musl-gcc" GCC="mips-openwrt-linux-musl-gcc" CXX="mips-openwrt-linux-musl-g++" RANLIB="mips-openwrt-linux-musl-gcc-ranlib" STRIP=mips-openwrt-linux-musl-strip OBJCOPY=mips-openwrt-linux-musl-objcopy OBJDUMP=mips-openwrt-linux-musl-objdump SIZE=mips-openwrt-linux-musl-size CROSS="mips-openwrt-linux-musl-" ARCH="mips" ;
make[3]: Entering directory `/home/leenchan/Desktop/op_dir/build_dir/target-mips_34kc_musl-1.1.10/chinadns-1.3.1'
make  all-recursive
make[4]: Entering directory `/home/leenchan/Desktop/op_dir/build_dir/target-mips_34kc_musl-1.1.10/chinadns-1.3.1'
Making all in src
make[5]: Entering directory `/home/leenchan/Desktop/op_dir/build_dir/target-mips_34kc_musl-1.1.10/chinadns-1.3.1/src'
mips-openwrt-linux-musl-gcc  -Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float -Wformat -Werror=format-security -Wl,-z,now -Wl,-z,relro   -L/home/leenchan/Desktop/openwrt/staging_dir/target-mips_34kc_musl-1.1.10/usr/lib -L/home/leenchan/Desktop/openwrt/staging_dir/target-mips_34kc_musl-1.1.10/lib -L/home/leenchan/Desktop/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.10/usr/lib -L/home/leenchan/Desktop/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.10/lib  -o chinadns chinadns.o  -lresolv 
chinadns.o: In function `main':
chinadns.c:(.text.startup+0xde4): undefined reference to `MAX'
collect2: error: ld returned 1 exit status
make[5]: *** [chinadns] Error 1
make[5]: Leaving directory `/home/leenchan/Desktop/op_dir/build_dir/target-mips_34kc_musl-1.1.10/chinadns-1.3.1/src'
make[4]: *** [all-recursive] Error 1
make[4]: Leaving directory `/home/leenchan/Desktop/op_dir/build_dir/target-mips_34kc_musl-1.1.10/chinadns-1.3.1'
make[3]: *** [all] Error 2
make[3]: Leaving directory `/home/leenchan/Desktop/op_dir/build_dir/target-mips_34kc_musl-1.1.10/chinadns-1.3.1'
make[2]: *** [/home/leenchan/Desktop/openwrt/build_dir/target-mips_34kc_musl-1.1.10/chinadns-1.3.1/.built] Error 2
make[2]: Leaving directory `/home/leenchan/Desktop/openwrt/feeds/leenchan/chinadns'
make[1]: *** [package/feeds/leenchan/chinadns/compile] Error 2
make[1]: Leaving directory `/home/leenchan/Desktop/openwrt'
make: *** [package/chinadns/compile] Error 2
make: Leaving directory `/home/leenchan/Desktop/openwrt'

any idea?

**Comment by shangjiyu** [comment]
as the log outpu 
```
chinadns.o: In function main': chinadns.c:(.text.startup+0xde4): undefined reference toMAX'
```
add below code could pass build through
```c
#ifndef max
    #define max(a,b) ((a) > (b) ? (a) : (b))
#endif
```

**Comment by leenchan** [comment]
compiled by adding the code.
but it does not work.
nslookup baidu.com get "(null)"
